# Generated by Django 4.2.15 on 2024-08-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=40)),
                ('estado_categoria', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'inactivo')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='palabraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_palabras', models.CharField(max_length=40)),
                ('estado_palabraCategoria', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'inactivo')], max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palabraCategoria', to='tuvooz.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_completos', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('contrasenna', models.CharField(max_length=13)),
                ('confirmacion_contrasenna', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='palabrasFavoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palabrasFavoritas', to='tuvooz.palabracategoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palabrasFavoritas', to='tuvooz.usuario')),
            ],
        ),
    ]
