# Generated by Django 3.2.14 on 2024-07-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_completos', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=60)),
                ('contrasenna', models.CharField(max_length=13)),
                ('confirmacion_contrasenna', models.CharField(max_length=50)),
                ('rol', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
