# Generated by Django 3.2.14 on 2024-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuvooz', '0002_auto_20240710_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=40)),
                ('estado_cetegoria', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'inactivo')], max_length=60)),
            ],
        ),
    ]
