# Generated by Django 3.2.14 on 2024-07-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuvooz', '0003_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='estado_cetegoria',
            new_name='estado_categoria',
        ),
        migrations.CreateModel(
            name='palabraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabras', models.CharField(max_length=40)),
                ('estado_palabraCategoria', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'inactivo')], max_length=60)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palabraCategoria', to='tuvooz.categoria')),
            ],
        ),
    ]
